export const state = {
    CONFIG: {},
    players: [],
    selectedPlayers: new Set(),
    allColumns: []
};

export const defaultSelectedColumnKeys = new Set([
    "PLAYER",
    "GAME_MODE",
    "CHAMPION",
    "DATE",
    "RESULT",
    "KILLS",
    "DEATHS",
    "ASSISTS"
]);

export const mockData = [
    {
        PLAYER: "efren",
        GAME_MODE: "CLASSIC",
        CHAMPION: "Ahri",
        DATE: "2026-04-01 21:14",
        RESULT: "Win",
        KILLS: 11,
        DEATHS: 3,
        ASSISTS: 8,
        DURATION: 1984,
        DOUBLE_KILLS: 1,
        TRIPLE_KILLS: 0,
        QUADRA_KILLS: 0,
        PENTA_KILLS: 0,
        LEGENDARY_KILLS: 0,
        DMG_TO_CHAMPS: 24511,
        DMG_TO_STRUCT: 2140,
        DMG_TAKEN: 16880,
        DMG_MITIGATED: 9200,
        GOLD: 14820,
        CREEP_SCORE: 194,
        DRAGONS: 1,
        BARONS: 0,
        LEVEL: 17,
        FIRST_BLOOD: "Assist",
        FIRST_TOWER: "False",
        SURRENDER: "False",
        TIME_CC_OTHER: 231,
        TIME_DEAD: 102,
        CRIT: 0,
        WARDS_PLACED: 9,
        WARDS_KILLED: 3
    },
    {
        PLAYER: "Luna",
        GAME_MODE: "ARAM",
        CHAMPION: "Lux",
        DATE: "2026-04-01 22:10",
        RESULT: "Loss",
        KILLS: 7,
        DEATHS: 9,
        ASSISTS: 19,
        DURATION: 1322,
        DOUBLE_KILLS: 0,
        TRIPLE_KILLS: 0,
        QUADRA_KILLS: 0,
        PENTA_KILLS: 0,
        LEGENDARY_KILLS: 0,
        DMG_TO_CHAMPS: 22100,
        DMG_TO_STRUCT: 420,
        DMG_TAKEN: 18911,
        DMG_MITIGATED: 6500,
        GOLD: 11340,
        CREEP_SCORE: 41,
        DRAGONS: 0,
        BARONS: 0,
        LEVEL: 15,
        FIRST_BLOOD: "False",
        FIRST_TOWER: "False",
        SURRENDER: "Early",
        TIME_CC_OTHER: 310,
        TIME_DEAD: 188,
        CRIT: 0,
        WARDS_PLACED: 2,
        WARDS_KILLED: 0
    },
    {
        PLAYER: "efren",
        GAME_MODE: "CLASSIC",
        CHAMPION: "Jinx",
        DATE: "2026-03-31 20:01",
        RESULT: "Win",
        KILLS: 18,
        DEATHS: 4,
        ASSISTS: 6,
        DURATION: 2244,
        DOUBLE_KILLS: 2,
        TRIPLE_KILLS: 1,
        QUADRA_KILLS: 0,
        PENTA_KILLS: 0,
        LEGENDARY_KILLS: 0,
        DMG_TO_CHAMPS: 33120,
        DMG_TO_STRUCT: 5500,
        DMG_TAKEN: 14550,
        DMG_MITIGATED: 4100,
        GOLD: 17600,
        CREEP_SCORE: 239,
        DRAGONS: 2,
        BARONS: 1,
        LEVEL: 18,
        FIRST_BLOOD: "True",
        FIRST_TOWER: "False",
        SURRENDER: "False",
        TIME_CC_OTHER: 94,
        TIME_DEAD: 121,
        CRIT: 812,
        WARDS_PLACED: 11,
        WARDS_KILLED: 4
    },
    {
        PLAYER: "ShadowFox",
        GAME_MODE: "URF",
        CHAMPION: "Zed",
        DATE: "2026-03-30 23:32",
        RESULT: "Loss",
        KILLS: 13,
        DEATHS: 11,
        ASSISTS: 5,
        DURATION: 1092,
        DOUBLE_KILLS: 1,
        TRIPLE_KILLS: 1,
        QUADRA_KILLS: 0,
        PENTA_KILLS: 0,
        LEGENDARY_KILLS: 0,
        DMG_TO_CHAMPS: 28771,
        DMG_TO_STRUCT: 1311,
        DMG_TAKEN: 19990,
        DMG_MITIGATED: 7200,
        GOLD: 15010,
        CREEP_SCORE: 102,
        DRAGONS: 0,
        BARONS: 0,
        LEVEL: 17,
        FIRST_BLOOD: "False",
        FIRST_TOWER: "Assist",
        SURRENDER: "False",
        TIME_CC_OTHER: 48,
        TIME_DEAD: 175,
        CRIT: 0,
        WARDS_PLACED: 4,
        WARDS_KILLED: 1
    },
    {
        PLAYER: "Astra",
        GAME_MODE: "CLASSIC",
        CHAMPION: "Thresh",
        DATE: "2026-03-30 18:05",
        RESULT: "Win",
        KILLS: 2,
        DEATHS: 5,
        ASSISTS: 24,
        DURATION: 2103,
        DOUBLE_KILLS: 0,
        TRIPLE_KILLS: 0,
        QUADRA_KILLS: 0,
        PENTA_KILLS: 0,
        LEGENDARY_KILLS: 0,
        DMG_TO_CHAMPS: 12440,
        DMG_TO_STRUCT: 590,
        DMG_TAKEN: 22150,
        DMG_MITIGATED: 28900,
        GOLD: 11120,
        CREEP_SCORE: 38,
        DRAGONS: 0,
        BARONS: 1,
        LEVEL: 16,
        FIRST_BLOOD: "Assist",
        FIRST_TOWER: "Assist",
        SURRENDER: "False",
        TIME_CC_OTHER: 514,
        TIME_DEAD: 164,
        CRIT: 0,
        WARDS_PLACED: 28,
        WARDS_KILLED: 8
    }
];

export const dom = {
    playerOptions: document.getElementById("playerOptions"),
    columnsContainer: document.getElementById("columnsContainer"),
    resultsHead: document.getElementById("resultsHead"),
    resultsBody: document.getElementById("resultsBody"),
    resultsSummary: document.getElementById("resultsSummary"),
    applyBtn: document.getElementById("applyBtn"),
    resetBtn: document.getElementById("resetBtn"),
    settingsToggle: document.getElementById("settingsToggle"),
    settingsToggleIcon: document.getElementById("settingsToggleIcon"),
    controlsPanel: document.getElementById("controlsPanel"),
    layout: document.querySelector(".layout")
};